name: FastAPI CI/CD

# Trigger workflow on push or pull request to the main branch
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # Set up and test FastAPI app
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9  # Specify Python version here

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        pytest tests/

  # # Deploy to Cloud (For example, using a simple server deployment)
  # deploy:
  #   runs-on: ubuntu-latest
  #   needs: build  # This means deploy will run after the build job

  #   steps:
  #   - name: Check out repository
  #     uses: actions/checkout@v2

  #   - name: Upload to cloud server
  #     run: |
  #       # Example deployment to a cloud server (for instance, AWS, DigitalOcean, or a VPS)
  #       ssh -i /path/to/your/private-key user@your-server-ip "cd /path/to/app && git pull && source venv/bin/activate && pip install -r requirements.txt && systemctl restart fastapi-app.service"

